name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Test
        run: make test

      - name: Publish
        run: make

      - name: Tar linux-x64 files
        run: |
          cd build
          tar cvf psxpackager-linux-x64{.tar,}
      - name: Upload linux-x64 Tar
        uses: actions/upload-artifact@v3
        with:
          name: psxpackager-linux-x64
          path: build/psxpackager-linux-x64.tar
      - name: Tar linux-arm files
        run: |
          cd build
          tar cvf psxpackager-linux-arm{.tar,}
      - name: Upload linux-arm Tar
        uses: actions/upload-artifact@v3
        with:
          name: psxpackager-linux-arm
          path: build/psxpackager-linux-arm.tar
      - name: Tar linux-arm64 files
        run: |
          cd build
          tar cvf psxpackager-linux-arm64{.tar,}
      - name: Upload linux-arm64 Tar
        uses: actions/upload-artifact@v3
        with:
          name: psxpackager-linux-arm64
          path: build/psxpackager-linux-arm64.tar
      - name: Tar osx-x64 files
        run : |
          cd build
          tar cvf psxpackager-osx-x64{.tar,}
      - name: Upload osx-x64 Tar
        uses: actions/upload-artifact@v3
        with:
          name: psxpackager-osx-x64
          path: build/psxpackager-osx-x64.tar
      - name: Tar osx-arm64 files
        run : |
          cd build
          tar cvf psxpackager-osx-arm64{.tar,}
      - name: Upload osx-arm64 Tar
        uses: actions/upload-artifact@v3
        with:
          name: psxpackager-osx-arm64
          path: build/psxpackager-osx-arm64.tar

